title: Zee Tax Professionals
# description: 
email: "azeem.rao@zeetechpartners.com"
copyright: Copyright &copy; 2020 Zee Tax Professionals. All rights reserved.
# google-analytics: 

baseurl: /zeetaxpros

# twitter: ""
# instagram: ""
# youtube: ""
# facebook: ""

plugins: 
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-seo-tag